using System.Globalization;
using Xunit;
using PtCalculator;

namespace PayrollCalculator.Tests;

/// <summary>
/// One row of PayrollVerificationTests/testdata/expected_results.csv.
/// Expected values are hand-computed for FY 2025-26 and must never be
/// regenerated by the calculator itself.
/// </summary>
public sealed record VerificationScenario(
    string EmployeeCode,
    string Name,
    string State,
    string TaxRegime,
    decimal MonthlyBasic,
    decimal MonthlyHra,
    decimal MonthlyDa,
    decimal MonthlySpecialAllowance,
    decimal MonthlyLta,
    decimal MonthlyOtherAllowances,
    decimal AnnualRentPaid,
    decimal Investment80C,
    decimal Investment80CCD1B,
    decimal Investment80D,
    decimal Investment80TTA,
    decimal HomeLoanInterest,
    bool IsFirstYearEmployee,
    bool HasDisability,
    int MonthNumber,
    decimal ExpectedGross,
    decimal ExpectedEmployeePF,
    decimal ExpectedEmployerPF,
    decimal ExpectedEmployeeESI,
    decimal ExpectedEmployerESI,
    decimal ExpectedPT,
    decimal ExpectedTDS,
    decimal ExpectedNetPay,
    string Notes)
{
    /// <summary>Hand-computed scenario id + name (used in failure messages).</summary>
    public override string ToString() => $"{EmployeeCode} {Name}";
}

/// <summary>
/// Verification suite: runs each hand-computed CSV scenario through
/// <see cref="PayrollCalculatorCore"/> and asserts every expected value within 0.01.
/// </summary>
public class PayrollVerificationTests
{
    private const decimal Tolerance = 0.01m;

    private static readonly string CsvPath = Path.Combine(
        AppContext.BaseDirectory, "PayrollVerificationTests", "testdata", "expected_results.csv");

    private static readonly List<VerificationScenario> AllScenarios = LoadScenarios();

    // ---------------- CSV loading ----------------

    public static TheoryData<VerificationScenario> Scenarios()
    {
        var data = new TheoryData<VerificationScenario>();
        foreach (var scenario in AllScenarios)
        {
            data.Add(scenario);
        }
        return data;
    }

    private static List<VerificationScenario> LoadScenarios()
    {
        if (!File.Exists(CsvPath))
        {
            throw new FileNotFoundException(
                "Verification CSV not found. Ensure it is copied to the test output directory.", CsvPath);
        }

        var data = new List<VerificationScenario>();
        string[] lines = File.ReadAllLines(CsvPath)
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .ToArray();

        string[] header = SplitCsvLine(lines[0]);
        foreach (string line in lines.Skip(1))
        {
            string[] fields = SplitCsvLine(line);
            if (fields.Length != header.Length)
            {
                throw new FormatException(
                    $"CSV row has {fields.Length} fields but header has {header.Length}: {line}");
            }

            data.Add(ParseRow(fields));
        }

        return data;
    }

    private static VerificationScenario ParseRow(string[] f)
    {
        static decimal Dec(string s) =>
            decimal.Parse(s.Trim(), CultureInfo.InvariantCulture);
        static bool Bool(string s) =>
            s.Trim().Equals("true", StringComparison.OrdinalIgnoreCase);

        return new VerificationScenario(
            EmployeeCode: f[0].Trim(),
            Name: f[1].Trim(),
            State: f[2].Trim(),
            TaxRegime: f[3].Trim(),
            MonthlyBasic: Dec(f[4]),
            MonthlyHra: Dec(f[5]),
            MonthlyDa: Dec(f[6]),
            MonthlySpecialAllowance: Dec(f[7]),
            MonthlyLta: Dec(f[8]),
            MonthlyOtherAllowances: Dec(f[9]),
            AnnualRentPaid: Dec(f[10]),
            Investment80C: Dec(f[11]),
            Investment80CCD1B: Dec(f[12]),
            Investment80D: Dec(f[13]),
            Investment80TTA: Dec(f[14]),
            HomeLoanInterest: Dec(f[15]),
            IsFirstYearEmployee: Bool(f[16]),
            HasDisability: Bool(f[17]),
            MonthNumber: int.Parse(f[18].Trim(), CultureInfo.InvariantCulture),
            ExpectedGross: Dec(f[19]),
            ExpectedEmployeePF: Dec(f[20]),
            ExpectedEmployerPF: Dec(f[21]),
            ExpectedEmployeeESI: Dec(f[22]),
            ExpectedEmployerESI: Dec(f[23]),
            ExpectedPT: Dec(f[24]),
            ExpectedTDS: Dec(f[25]),
            ExpectedNetPay: Dec(f[26]),
            Notes: f[27].Trim());
    }

    /// <summary>Quote-aware CSV field splitter (handles commas inside quotes).</summary>
    private static string[] SplitCsvLine(string line)
    {
        var fields = new List<string>();
        var current = new System.Text.StringBuilder();
        bool inQuotes = false;

        foreach (char c in line)
        {
            if (c == '"')
            {
                inQuotes = !inQuotes;
            }
            else if (c == ',' && !inQuotes)
            {
                fields.Add(current.ToString());
                current.Clear();
            }
            else
            {
                current.Append(c);
            }
        }
        fields.Add(current.ToString());
        return [.. fields];
    }

    // ---------------- The verification ----------------

    [Theory]
    [MemberData(nameof(Scenarios))]
    public void HandComputedScenario_MatchesCalculator(VerificationScenario s)
    {
        // The CSV deliberately has no IsMetro column: all scenarios assume non-metro
        // (40% HRA cap). Rent is zero in every scenario, so the cap never applies anyway.
        Assert.True(
            PtCalculatorCore.TryParseState(s.State, out PtState state),
            $"[{s}] Unknown state \"{s.State}\" in CSV.");

        Employee employee = new(
            EmployeeId: s.EmployeeCode,
            Name: s.Name,
            State: state,
            IsMetro: false,
            TaxRegime: s.TaxRegime.Equals("Old", StringComparison.OrdinalIgnoreCase)
                ? TaxRegime.Old
                : TaxRegime.New,
            MonthlyBasic: s.MonthlyBasic,
            MonthlyHra: s.MonthlyHra,
            MonthlyDa: s.MonthlyDa,
            MonthlySpecialAllowance: s.MonthlySpecialAllowance,
            MonthlyLta: s.MonthlyLta,
            MonthlyOtherAllowances: s.MonthlyOtherAllowances,
            AnnualRentPaid: s.AnnualRentPaid,
            Section80C: s.Investment80C,
            Section80CCD1B: s.Investment80CCD1B,
            Section80D: s.Investment80D,
            Section80TTA: s.Investment80TTA,
            HomeLoanInterest: s.HomeLoanInterest,
            IsFirstYearEmployee: s.IsFirstYearEmployee,
            HasDisability: s.HasDisability,
            MonthNumber: s.MonthNumber);

        PayrollSlip slip = PayrollCalculatorCore.Calculate(employee);

        var mismatches = new List<string>();

        Check("ExpectedGross", s.ExpectedGross, slip.GrossMonthlySalary);
        Check("ExpectedEmployeePF", s.ExpectedEmployeePF, slip.EmployeePf);
        Check("ExpectedEmployerPF", s.ExpectedEmployerPF, slip.EmployerEps + slip.EmployerEpf);
        Check("ExpectedEmployeeESI", s.ExpectedEmployeeESI, slip.EmployeeEsi);
        Check("ExpectedEmployerESI", s.ExpectedEmployerESI, slip.EmployerEsi);
        Check("ExpectedPT", s.ExpectedPT, slip.ProfessionalTax);
        Check("ExpectedTDS", s.ExpectedTDS, slip.Tds);
        Check("ExpectedNetPay", s.ExpectedNetPay, slip.NetMonthlyTakeHome);

        if (mismatches.Count > 0)
        {
            Assert.Fail(
                $"Scenario {s} ({s.TaxRegime} regime - {s.Notes}) mismatched:\n" +
                string.Join("\n", mismatches));
        }

        void Check(string column, decimal expected, decimal actual)
        {
            if (Math.Abs(expected - actual) > Tolerance)
            {
                mismatches.Add(
                    $"  {column}: expected {expected.ToString("N2", CultureInfo.InvariantCulture)} " +
                    $"but actual was {actual.ToString("N2", CultureInfo.InvariantCulture)} " +
                    $"(diff {(actual - expected).ToString("N2", CultureInfo.InvariantCulture)})");
            }
        }
    }

    // Sanity: the CSV really contains the 10 required scenarios.
    [Fact]
    public void Csv_ContainsTenScenarios()
    {
        var scenarios = AllScenarios;

        Assert.Equal(10, scenarios.Count);
        Assert.Equal(
            ["VER001", "VER002", "VER003", "VER004", "VER005",
             "VER006", "VER007", "VER008", "VER009", "VER010"],
            scenarios.Select(s => s.EmployeeCode));
    }
}
